language: php
sudo: false
dist: trusty
php:
  - '7.1'
  - '7.2'
  - '7.3'
install:
  - travis_retry composer install
script:
  - vendor/bin/phpunit
  - vendor/bin/ecs check src/
  - vendor/bin/phpmd src/ text cleancode, codesize, controversial, design, naming, unusedcode
  - vendor/bin/phpstan analyze --level max src/
